STOPWORDS = {
    "a",
    "an",
    "and",
    "any",
    "for",
    "group",
    "individuals",
    "of",
    "old",
    "olds",
    "people",
    "person",
    "persons",
    "population",
    "profile",
    "profiles",
    "records",
    "the",
    "to",
    "users",
    "with",
    "year",
    "years",
}


VALID_GENDERS = {"male", "female"}
VALID_AGE_GROUPS = {"child", "teenager", "adult", "senior"}


SORT_COLUMN_MAP = {
    "age": "age",
    "created_at": "created_at",
    "gender_probability": "gender_probability",
}


COUNTRY_KEYWORDS = {
    "nigeria": "NG",
    "kenya": "KE",
    "angola": "AO",
    "benin": "BJ",
    "ghana": "GH",
    "uganda": "UG",
    "tanzania": "TZ",
    "south africa": "ZA",
    "zambia": "ZM",
    "zimbabwe": "ZW",
    "ethiopia": "ET",
    "cameroon": "CM",
    "senegal": "SN",
    "ivory coast": "CI",
    "cote d'ivoire": "CI",
    "cote divoire": "CI",
    "rwanda": "RW",
    "burundi": "BI",
    "algeria": "DZ",
    "morocco": "MA",
    "egypt": "EG",
    "tunisia": "TN",
    "namibia": "NA",
    "botswana": "BW",
    "sierra leone": "SL",
    "liberia": "LR",
    "mali": "ML",
    "burkina faso": "BF",
    "chad": "TD",
    "niger": "NE",
    "congo": "CG",
    "dr congo": "CD",
    "democratic republic of congo": "CD",
    "united states": "US",
    "usa": "US",
    "canada": "CA",
    "united kingdom": "GB",
    "uk": "GB",
    "france": "FR",
    "germany": "DE",
    "italy": "IT",
    "spain": "ES",
    "portugal": "PT",
    "india": "IN",
    "china": "CN",
    "japan": "JP",
    "brazil": "BR",
    "mexico": "MX",
    "argentina": "AR",
}


COUNTRY_NAME_BY_ID = {
    "NG": "Nigeria",
    "KE": "Kenya",
    "AO": "Angola",
    "BJ": "Benin",
    "GH": "Ghana",
    "UG": "Uganda",
    "TZ": "Tanzania",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    "ET": "Ethiopia",
    "CM": "Cameroon",
    "SN": "Senegal",
    "CI": "Cote d'Ivoire",
    "RW": "Rwanda",
    "BI": "Burundi",
    "DZ": "Algeria",
    "MA": "Morocco",
    "EG": "Egypt",
    "TN": "Tunisia",
    "NA": "Namibia",
    "BW": "Botswana",
    "SL": "Sierra Leone",
    "LR": "Liberia",
    "ML": "Mali",
    "BF": "Burkina Faso",
    "TD": "Chad",
    "NE": "Niger",
    "CG": "Congo",
    "CD": "Democratic Republic of the Congo",
    "US": "United States",
    "CA": "Canada",
    "GB": "United Kingdom",
    "FR": "France",
    "DE": "Germany",
    "IT": "Italy",
    "ES": "Spain",
    "PT": "Portugal",
    "IN": "India",
    "CN": "China",
    "JP": "Japan",
    "BR": "Brazil",
    "MX": "Mexico",
    "AR": "Argentina",
}


COUNTRY_ADJECTIVE_KEYWORDS = {
    "nigerian": "NG",
    "kenyan": "KE",
    "angolan": "AO",
    "beninese": "BJ",
    "ghanaian": "GH",
    "ugandan": "UG",
    "tanzanian": "TZ",
    "south african": "ZA",
    "zambian": "ZM",
    "zimbabwean": "ZW",
    "ethiopian": "ET",
    "cameroonian": "CM",
    "senegalese": "SN",
    "ivorian": "CI",
    "rwandan": "RW",
    "burundian": "BI",
    "algerian": "DZ",
    "moroccan": "MA",
    "egyptian": "EG",
    "tunisian": "TN",
    "namibian": "NA",
    "botswanan": "BW",
    "sierra leonean": "SL",
    "liberian": "LR",
    "malian": "ML",
    "burkinabe": "BF",
    "chadian": "TD",
    "nigerien": "NE",
    "congolese": "CG",
    "american": "US",
    "canadian": "CA",
    "british": "GB",
    "french": "FR",
    "german": "DE",
    "italian": "IT",
    "spanish": "ES",
    "portuguese": "PT",
    "indian": "IN",
    "chinese": "CN",
    "japanese": "JP",
    "brazilian": "BR",
    "mexican": "MX",
    "argentinian": "AR",
}


GENDER_KEYWORDS = {
    "male": "male",
    "males": "male",
    "man": "male",
    "men": "male",
    "boy": "male",
    "boys": "male",
    "female": "female",
    "females": "female",
    "woman": "female",
    "women": "female",
    "girl": "female",
    "girls": "female",
}


AGE_GROUP_KEYWORDS = {
    "child": "child",
    "children": "child",
    "baby": "child",
    "infant": "child",
    "toddler": "child",
    "kid": "child",
    "kids": "child",
    "teen": "teenager",
    "teens": "teenager",
    "teenager": "teenager",
    "teenagers": "teenager",
    "adult": "adult",
    "adults": "adult",
    "senior": "senior",
    "seniors": "senior",
    "elderly": "senior",
    "old": "senior",
    "elders": "senior",
    "old-timer": "senior",
}


YOUNG_KEYWORDS = {
    "young",
    "youth",
    "youths",
    "juvenile",
    "juveniles",
    "adolescent",
    "adolescents",
}